package models

import (
	"time"
)

// Account represents the account schema in the database
type Account struct {
	ID                string  `gorm:"primaryKey;type:uuid;default:uuid_generate_v4()"` // Primary key, UUID generated by the database
	UserID            string  `gorm:"not null"`                                       // Foreign key to the User table
	Type              string  `gorm:"type:text;not null"`                             // Type of account (e.g., OAuth, email)
	Provider          string  `gorm:"type:text;not null"`                             // Provider name (e.g., Google, GitHub)
	ProviderAccountID string  `gorm:"type:text;not null"`                             // Unique provider account ID
	RefreshToken      *string `gorm:"type:text"`                                      // Nullable refresh token
	AccessToken       *string `gorm:"type:text"`                                      // Nullable access token
	ExpiresAt         *int64  `gorm:"type:bigint"`                                    // Nullable expiration timestamp
	TokenType         *string `gorm:"type:text"`                                      // Nullable token type
	Scope             *string `gorm:"type:text"`                                      // Nullable scope of the account
	IDToken           *string `gorm:"type:text"`                                      // Nullable ID token
	SessionState      *string `gorm:"type:text"`                                      // Nullable session state
	CreatedAt         time.Time `gorm:"autoCreateTime"`                                // Auto-generated creation timestamp
	UpdatedAt         time.Time `gorm:"autoUpdateTime"`                                // Auto-updated modification timestamp
	User              User    `gorm:"constraint:OnDelete:CASCADE"`                    // Belongs to User

	// Composite unique constraint for provider and ProviderAccountID
	ProviderProviderAccountIDConstraint string `gorm:"uniqueIndex:unique_provider_provider_account_id"`
}